### PR TITLE
add dhcp Class ID option support.

### PR DESCRIPTION
**Pull request by rzrabi**

### CODE REVIEW

**Comment by hhaim** [comment]
@rzrabi 
please consider this 

[branch](https://github.com/hhaim/trex-emu/tree/rzrabi-DHCPOptionsClassIDSupport)

1) Use git beautify for tabs/spaces (vscode is doing this automaticly)
2) Use json pointers to identify if an option was provided
3) Encapsulate the  options into one struct 
4) Add a test for the new options 

Need to fix the client code (python)

**Comment by bdollma** [comment]
Hi @rzrabi,
I am missing to why your DHCP feature changes IPFix/Netflow files?
Thanks,

**Comment by rzrabi** [comment]
> Hi @rzrabi,
> I am missing to why your DHCP feature changes IPFix/Netflow files?
> Thanks,

reverted

**Comment by hhaim** [comment]
rebased

**Pull request closed without merging**
