### PR TITLE
PPP Plugin implementation for TRex EMU

### PR DESCRIPTION
**Pull request by vmarrazz**
- added necessary ppp layers to gopacket.
- implemented point2point plugin
- integrated point2point plugin into trex-emu
- added sample usage script in Python

Signed-off-by: Vincenzo Marrazzo <vincenzo.marrazzo@capgemini.com>

### CODE REVIEW

**Comment by hhaim** [comment]
@vmarrazz thanks. 
Rebased but didn't test it yet. 
A few comments

1. There is no unit-test and the 
2. I change the location of the example script, suggest to add a SDK help to the plugin in trex-core
2. Add an example profile in trex-core (scripts/emu)
3. Add a documentation and how to test it using Linux (is there a pppoe server /docker)?
4. Replaced the log to be -> none as we don't have a logger yet
5. We try in other plugins not to allocate and build packets on the fly, this is very heavy from the resource 
6. There is no need to restart the timer every packet send. You can inc a counter and check on the event. restart is heavy

**Comment by vmarrazz** [comment]
Hi @hhaim

Many thanks on your comments. Below my first analisys. 

1. YES you are right. To add UT I need to study how you have approached "veth mock" to simulate answers from dut.
2. Ok for file location. For sdk help do you mean a wiki?
3. Do you mean python file with implementation of class Prof1?
4. It's a good request! My dut is a ppp relay between CPE and radius. I have developed this plugins using only dut and I can't share a test procedure based on it. 😅
5. Also for my development there isn't a real logger, I have used println method and I agree this logging approach can overwhelm the existing stdout redirection. Waiting for official logger, I can stop println and enable it only when a debug flag is passed via command line. Do you agree this temp solution?
6. Ok I understand your point on computational load, therefore this kind of plugin has many dynamic fields... Client mac, server mac, session id...etc. Maybe I understand wrong and please provide me other details on what do you mean.
7. This is a good observation to be implemented soon.

Regards
Vincenzo

**Comment by hhaim** [comment]
@vmarrazz 

1) there is no need for muck, you can even capture the traffic and make it as a golden (it is captured to json)
you can inspect it and record it as a test. the problem right now that there is **zero** tests and even the 2 tests that you crashed

2) profiles example we put here
https://github.com/cisco-system-traffic-generator/trex-core/tree/master/scripts/emu 

sdk doc here 
https://github.com/cisco-system-traffic-generator/trex-core/tree/master/scripts/automation/trex_control_plane/doc_emu/api/plugins

and of course a tutorial in the main doc here
https://github.com/cisco-system-traffic-generator/trex-emu/blob/master/doc/trex_emu.asciidoc

3) this code should work with linux PPPoe implementation right? worth checking it and write how you did it (maybe with docker)

4) I think that I missed a much bigger problem! I'm not a PPPoE expert but
PPPoE is L2 and it is much like a tunnel (dot1q), so all the other plugins should work with it once it is enabled. 
or example UDP socket should have ```eth/pppoe/ip/udp``` and right now, the code will not generate it ( instead ```eth/pppoe/ip/udp```)

what about multicast (IGMP? MLD? DHCP?)

**Comment by bdollma** [comment]
Salve @vmarrazz,
First of all, thank you for your commit. We appreciate you taking the time and contributing to the project.
There are a few minor things I am trying to understand from looking at your code, not even regarding PPP implementation but general guidelines.
1. Why did you add a "release" flag to the utility script? There is a build flag, and the build flag updates the version/build date and Git-SHA. This is actually redundant and creates mass confusion since now we have to version.go files (one is committed and one is not).
2. I am wondering why do you need to add line numbers in copyright messages, like this for example:
`added RandMACKey function at line 630`. You can gladly add a line like this: `added RandMACKey function` but line numbers are not maintainable. If tomorrow we add a function in the code before your function, we need to update the comments, and this is simply not maintainable. 
3. What is the status of comments like this: `MANCA rfc1661 FATTO`? It is a bit confusing, not only because it is Italian, but because se è fatto allora non manca. Anyway, there are a lot of comments left around in the code which we can clean but we don't want to clean comments which can be important for you, so we would appreciate if you can take the time to review it.
Thanks again,
Best,

**Comment by vmarrazz** [comment]
Hi @hhaim 
1. I analisys how capture/prepare golden traffic/json for UT.
2. I analisys how to prepare profile and manuals related this plugin
3. I am evaluating a Docker based solution that carry on PPPoE implementation. I have at moment two alternatives to be dockerized https://accel-ppp.org/ or "MPD PPP deamon".... I will inform you
4. I see your point, it's releated to pipe multiple plugins into EMU. 
I need an analisys to better understand this feature of EMU and propose some examples.  For sure ICMP is a good example eth/ppp/icmp to evaluate a pipe with point2point. I think also IGMP can be a good example. Related DHCP I don't understand if applicabile, I think that PPP and DHCP cant coexist in same scenario.... but maybe I am wrong.

Regards
Vincenzo

Hi @bdollma,
Thanks for your interesting observation
1. I have developed starting from v2.81 of code and I don't update it anymore. I see your approach and I prefer it, because avoiding a file to be monitored by Git.
2. I agree and the line numbers are added only for "presentation" of modified part (In PS I add a link that suggest me this approach). Into next commit I will remove line numbers.
3. It's a personal note used to track missing rfc. It must be removed because I miss to remove it.

Regards
Vincenzo

PS for point 2 -> :-)
https://www.entrepreneur.com/article/232420#:~:text=Buried%20amongst%20dozens%20of%20points,full%20expense%20of%20the%20promoter.

**Pull request closed without merging**
